version: "3.8"
services:
  # oauth 서비스에서 가져옴
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: jp3pe/belf-kr/storage-mysql-service
    container_name: mysql-storage-dev
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    command:
      # 한글과 이모지 입력을 위하여 기본 문자셋 인코딩 변경
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  storage-service:
    depends_on:
      - mysql
    build:
      context: "./"
      dockerfile: Dockerfile
    image: "jp3pe/belf-kr/storage-service"
    container_name: "belf-storage-service"
    environment:
      - STORAGE_SERVICE_PORT=8000
      - STORAGE_SERVICE_ACCESS_LOG=true
      - STORAGE_SERVICE_UPLOAD_PATH=/home/sanic/project/upload
      - STORAGE_SERVICE_DB_HOST=host.docker.internal
      - STORAGE_SERVICE_DB_PORT=3307
      - STORAGE_SERVICE_DB_NAME=belf
      - STORAGE_SERVICE_DB_USER=root
      - STORAGE_SERVICE_DB_PASSWORD=example
    ports:
      - "3004:8000"
    volumes:
      - "./upload:/home/sanic/project/upload"
    command: "python main.py"
