apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-service-static-files
  namespace: qa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: belf-azurefiles
  resources:
    requests:
      storage: 1Gi
