apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oauth-server
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      containers:
        - name: oauth-server
          image: ghcr.io/belf-kr/oauth-server/gin
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-server
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: oauth-server
